sonar.projectKey=md-sadidtahsin_assignment-14
sonar.organization=md-sadidtahsin
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**